version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: docker-maps
    restart: always
    working_dir: /usr/src/app
    environment:
      - PORT:3000
      - env:production
    ports:
      - 3001:3000
    command: npm run start